pequeños avances :D
JavierMarrero/jlibgraph pull request #51
Opened 2022-11-15 04:09 UTC by SnowBlackQueen

kosaraju casi listo, dial con ideas! basta x ahora, tengo mucho sueño 🥲

2022-11-15 16:35 UTC, JavierMarrero commented
Ok, voy a revisar ahora 👍🏼

2022-11-15 16:37 UTC, JavierMarrero reviewed
Voy a dejar el pull abierto sin aprobarlo específicamente. Cuando termines Kosaraju no hagas un nuevo pull, solo haz push y ya se actualizará aquí.

2022-11-15 17:13 UTC, cdrobaina01 requested changes
Lo mismo q @JavierMarrero, si quieren tener las cosas guardadas en github pues recomiendo mejor que lo mantengan en su fork y reserven las pull request para cambios terminados, o al menos pequeños módulos terminados dentro de los algoritmos.
Además te recuerdo lo de los iteradores en los parámteros del constructor. Por último un detallito en los parámetros del constructor de `Kosaraju`. El grafo se lo pasas como segundo parámetro, me parece que todos los demás algoritmos reciben el grafo como primer parámetro, lo cual podría causar confusión o errores en los usuarios de la librería.

2022-11-15 17:23 UTC, JavierMarrero commented
La verdad válido el comentario de @cdrobaina01 sobre el orden de los parámetros en el constructor. Aunque parezca un cambio poco importante, es buena práctica mantener los parámetros de las funciones estables.

2022-11-17 23:57 UTC, JavierMarrero approved these changes
En Internet, nadie sabe que eres un perro. 👀

2022-11-17 23:58 UTC, merged